HOST_SQUASHFS_VERSION = 4.3
HOST_SQUASHFS_SOURCE = host-squashfs$(HOST_SQUASHFS_VERSION)
HOST_SQUASHFS_ARCHIVE = squashfs$(HOST_SQUASHFS_VERSION).tar.gz
HOST_SQUASHFS_PATCH = 
HOST_SQUASHFS_DEPENDENCIES = host-lzo

HOST_SQUASHFS_MAKE_OPTS = \
	LZO_SUPPORT=1 \
	COMP_DEFAULT=lzo \
	EXTRA_CFLAGS="$(HOST_CFLAGS)" \
	EXTRA_LDFLAGS="$(HOST_LDFLAGS)"

define HOST_SQUASHFS_BUILD_CMD
	$(HOST_MAKE_ARGS) $(MAKE) $(HOST_SQUASHFS_MAKE_OPTS) -C $(HOST_SQUASHFS_DIR)/squashfs-tools
endef

define HOST_SQUASHFS_INSTALL_TARGET_CMD
	$(HOST_MAKE_ARGS) $(MAKE) $(HOST_SQUASHFS_MAKE_OPTS) INSTALL_DIR=$(HOST_DIR)/usr/bin -C $(HOST_SQUASHFS_DIR)/squashfs-tools install
endef

define HOST_SQUASHFS_CLEAN_CMD
	$(HOST_MAKE_ARGS) $(MAKE) $(HOST_SQUASHFS_MAKE_OPTS) -C $(HOST_SQUASHFS_DIR)/squashfs-tools clean
endef

$(eval $(add-host-generic-package))

MKSQUASHFS = $(HOST_DIR)/usr/bin/mksquashfs
UNSQUASHFS = $(HOST_DIR)/usr/bin/unsquashfs
