SQLITE_VERSION = 3080900
SQLITE_SOURCE = $(SQLITE_NAME)-autoconf-$(SQLITE_VERSION)
SQLITE_ARCHIVE = $(SQLITE_SOURCE).tar.gz
SQLITE_PATCH = 
SQLITE_DEPENDENCIES = 

SQLITE_INSTALL_STAGING = YES

SQLITE_CONFIGURE_OPTS = \
	--localstatedir=/var

define SQLITE_INSTALL_TARGET_CMD
	$(TARGET_MAKE_ARGS) $(SQLITE_MAKE) -C $(SQLITE_DIR) DESTDIR=$(TARGET_DIR) install
	$(CHMOD) +w $(TARGET_DIR)/usr/lib/libsqlite3.so*
endef

$(eval $(add-autotools-package))
