PERSIST_TOOL_VERSION = 0.0.6
PERSIST_TOOL_SOURCE = $(PERSIST_TOOL_NAME)-$(PERSIST_TOOL_VERSION)
PERSIST_TOOL_ARCHIVE = $(PERSIST_TOOL_SOURCE).tar.xz
PERSIST_TOOL_PATCH = 
PERSIST_TOOL_DEPENDENCIES = host-pkgconf eventlog libglib2 syslog-ng

$(eval $(add-autotools-package))
